version: "4.0"
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cinemao
    ports:
        - "5000:5432"
    volumes:
        - ./data:/var/lib/postgresql/data